# Generated by Django 5.2.6 on 2025-09-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='download_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
